openapi: 3.1.0
info:
  title: api-title
  version: '1.0'
  description: API Template
servers:
  - url: 'http://localhost:5001'
paths:
  /user:
    post:
      summary: Create New User
      operationId: user_create
      responses:
        '204':
          description: No content.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      tags:
        - User
    get:
      summary: ''
      operationId: user_getAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      description: Gets all users.
      tags:
        - User
    parameters: []
  '/user/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get a user
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      operationId: user_get
      description: Get a user.
    put:
      summary: ''
      operationId: user_update
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      description: Update a user's information.
    delete:
      summary: ''
      operationId: user_delete
      responses:
        '204':
          description: No Content
      description: Delete a user.
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: string
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
      required:
        - firstName
        - lastName
tags:
  - name: User
